### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by cvweiss** [EVE-KILL/zKillboard#207]
Implement

Here are some ideas:
- Lost 10 Plex
- Solo Killed a ship class at least 2 sizes larger 
- 1000 kills
- 1000 losses
- Losing a ship with more than 10 prisoners aboard.. Call it.. Prison Transport! aw yeaaaaa _shades_
- Cards from Rixx Javix?

**Comment by karbowiak** [comment]
zz_achievements(achievementID, achievementName, achievementDescription)
zz_achievements_list(characterID, achievementID)

cli_achievements.php has a list of all the queries to run pr. character, to figure out if the user is up for a certain achievement.
