### ISSUE TITLE
Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY'

### ISSUE THREAD

**Issue by MaxRink** [EVE-KILL/zKillboard#272]
Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/zKillboard/vendor/cvweiss/zlibrary/src/Db.php on line 45
Try to run the Cronjob, but getting this error
Running MariaDB, nginx and HHVM on Ubuntu 14.04

**Comment by karbowiak** [comment]
Closing for lack of response
