### ISSUE TITLE
API: kills on shipTypeID dosent seem to work

### ISSUE THREAD

**Issue by LewisMcMahon** [EVE-KILL/zKillboard#279]
https://beta.eve-kill.net/api/kills/shipTypeID/23919,23913,22852,23917,11567,3764,23773,671/page/1/

Its supposed to return just kills of the above shiptypes but it dosent.

**Comment by karbowiak** [comment]
After looking into this, i've figured out that.

1. Kills shows killmails where they are involved
2. Losses shows kills where the victim was in said ship.

So you want to use losses when trying to get shipTypeID kills :)
