### ISSUE TITLE
Json has \ in it

### ISSUE THREAD

**Issue by LewisMcMahon** [EVE-KILL/zKillboard#285]
it looks like for some reason the json from the api is "escaping" the quote marks with a \ see;
https://beta.eve-kill.net/api/losses/shipTypeID/23919,23913,22852,23917,11567,3764,23773,671,3514/page/1/

**Comment by karbowiak** [comment]
It shouldn't affect the result tho, is it?

lør. 10. jan. 2015 00.59 skrev Lewis McMahon <notifications@github.com>:

**Comment by LewisMcMahon** [comment]
it seems to be, its returning stuff like this \"killID\":43674179 and those quotes should not be escaped as far as i can tell?

**Comment by karbowiak** [comment]
ok, i think i know whats up, i'll have it fixed asap! :)
