### ISSUE TITLE
Id types in api are not consistent

### ISSUE THREAD

**Issue by LewisMcMahon** [EVE-KILL/zKillboard#286]
sometimes ids are show as ints with no " and sometimes strings with a " see:
https://zkillboard.com/api/losses/shipTypeID/3764,23773,671,11567,23917,22852,23913,23919,3514/page/

Search for 99004901 the alliance id of Snuffed Out in some kill mails it contained in "" others it is not.

**Comment by karbowiak** [comment]
I only JUST noticed you're poking zkillboard.com and not beta.eve-kill.net.. duh..

But i fixed the issue on beta.eve-kill.net, so there's that :P
