### ISSUE TITLE
Missing table (ccp_zship_search)

### ISSUE THREAD

**Issue by ovnr** [EVE-KILL/zKillboard#303]
The installer isn't creating a table (used by cron/hourly and autocomplete): ccp_zship_search. 

Definition:
CREATE TABLE `ccp_zship_search` (
        `typeID` INT(16) NOT NULL DEFAULT '0',
        PRIMARY KEY (`typeID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

**Comment by karbowiak** [comment]
Fixed with a65b7ffa9ed94ac4a8a10d0acfbf7f33c9e7db3d
