### ISSUE TITLE
(possible PEBKAC) zCache isn't autodetecting memcache and defaults to FileCache

### ISSUE THREAD

**Issue by ovnr** [EVE-KILL/zKillboard#304]
Haven't tried reproducing it, but happened on a fresh install. Forcing $preferredCache to "Memcache" in /classes/Cache.php:34 makes it use Memcache without any issues.

Also, should put a more clear note about using a memcache/redis/etc install - I initially ignored it because I'm running a low-traffic KB, but it will spam your filesystem to *death* with temp files if you use the fallback FileCache mode.

**Comment by karbowiak** [comment]
Should be fixed with push 2c2a4bf1698f9e9c6a0654d1bdd993747f645320
