### ISSUE TITLE
API: Requests for old data return errors, malformed SQL

### ISSUE THREAD

**Issue by CaptainThunk** [EVE-KILL/zKillboard#310]
For example, the URL:
https://zkillboard.com/api/shipTypeID/671/startTime/200701010000/endTime/200701012359/orderDirection/asc/

Results in:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and p.killID <= order by p.killID asc limit 0, 200' at line 1

Another example is:
https://zkillboard.com/api/no-items/shipTypeID/671/page/1/startTime/200701010000/endTime/200801010000/orderDirection/asc/

Which results with:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and p.killID <= 362841 order by p.killID asc limit 0, 200' at line 1

As far as I know, this is recent as it wasn't doing this last week.

**Comment by CaptainThunk** [comment]
https://zkillboard.com/api/shipTypeID/671/startTime/201504050000/endTime/201504052359/orderDirection/asc/

Returns 0 results, yet:
https://zkillboard.com/api/shipTypeID/671/startTime/201504050001/endTime/201504060000/orderDirection/asc/

Returns many.

**Comment by cvweiss** [comment]
Fixed on zkillboard.com (you wrote this issue in the wrong repo, but thats ok)

**Comment by karbowiak** [comment]
All the endpoints work fine on https://beta.eve-kill.net/

https://beta.eve-kill.net/api/combined/shipTypeID/671/startTime/200701010000/endTime/200701012359/orderDirection/asc/

https://beta.eve-kill.net/api/combined/no-items/shipTypeID/671/page/1/startTime/200701010000/endTime/200801010000/orderDirection/asc/

https://beta.eve-kill.net/api/combined/shipTypeID/671/startTime/201504050000/endTime/201504052359/orderDirection/asc/

https://beta.eve-kill.net/api/combined/shipTypeID/671/startTime/201504050001/endTime/201504060000/orderDirection/asc/

Enjoy! ;)
