### ISSUE TITLE
[Bug] Looking at Alliance or Corp Overview throws POD exception

### ISSUE THREAD

**Issue by fastgar** [EVE-KILL/zKillboard#311]
http://eve-rovai.de/corporation/1000167/

Perhaps i overlook or miss something.

**Comment by karbowiak** [comment]
Hmm, that is a good question.

Are you running MariaDB?

**Comment by fastgar** [comment]
Yes,
5.5.41-MariaDB

**Comment by sn0opy** [comment]
Hm, looks like you missed something else too. 
`Notice: Undefined variable: rawKillmailParser in /var/www/html/zKillboard/twig.php on line 143`

Beside that, is zz_alliances and zz_corporations even populated?

**Comment by fastgar** [comment]
Regarding the zkb.log yes.
20150420 15:15:20 Alliance tables repopulated - 3,081 active Alliances with a total of 13,568 Corporations.
Give me a minute to look into the db.

**Comment by karbowiak** [comment]
regarding the rawKillmailParser i seem to have forgotten to add $rawKillmailParser = false; to the default config, oops.

As for the error you're seeing, could you try and echo out the query? (line 105, add echo $query;)

Would help nail it down, cause i've never seen that exact bug before /o\

**Comment by fastgar** [comment]
So the command is inserted, but there is the echo displayed.
Have no clue for php^^

**Comment by karbowiak** [comment]
oh i see where the issue is.. give me a few and i'll fix it

**Comment by karbowiak** [comment]
Should be fixed with ac67f48f3b4eec1e39ce8b2fa3e2d87459511131

Try and issue a git reset --hard and git pull

**Comment by fastgar** [comment]
nope not working

**Comment by karbowiak** [comment]
Doesn't look like you've pulled the changes.

Are you sure it's this repo you're using and not the one Squizz i maintaining?

**Comment by fastgar** [comment]
remote origin
  Fetch URL: https://github.com/EVE-KILL/zKillboard
  Push  URL: https://github.com/EVE-KILL/zKillboard
  HEAD branch: master
  Remote branches:
    campaigns tracked
    installer tracked
    master    tracked
    theme     tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)


chris@h2288512:/var/www/html# git pull
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/EVE-KILL/zKillboard
   3e8580a..ac67f48  master     -> origin/master
Updating 3e8580a..ac67f48
Fast-forward
 install/config.new.php |   9 ++-
 view/overview.php      | 193 ++++++++++++++++++++++++++++++++++++++-------------------------
 2 files changed, 122 insertions(+), 80 deletions(-)

the echo %query is inserted by me

**Comment by karbowiak** [comment]
Hm, ok, had to ask :D

But why is the code shown by the debug page showing

```
		$filter = "{$key}ID = :id";
}
if ($filter != "") {
	$minKillID = Db::queryField("select min(killID) killID from zz_participants where dttm >= date_sub(now(), interval 90 day) and dttm < date_sub(now(), interval 89 day)", "killID", array(), 900);
	$hasSupers = Db::queryField("select killID from zz_participants where isVictim = 0 and groupID in (30, 659) and $filter and killID > $minKillID limit 1", "killID", array(":id" => $id));
	$extra["hasSupers"] = $hasSupers > 0;
	$extra["supers"] = array();
```

then, hmm.. very weird

**Comment by fastgar** [comment]
for you convinence i retypted the git commands :D

chris@h2288512:/var/www/html# git reset --hard
HEAD is now at ac67f48 If the minKillID for supercap lookup is 0, then supers is zero
chris@h2288512:/var/www/html# git pull
Already up-to-date.

**Comment by karbowiak** [comment]
/o\

No idea then, it should have the new code (which was pushed down to line 260 something)
Which checks if the minKillID is zero, and then omits querying for supers if it is.

You can try and replace the entire overview.php with:
http://pastebin.com/4gmq835R

Just to check i guess ? :D

**Comment by fastgar** [comment]
Relacing worked lol :D 
with the query displayed^^

**Comment by karbowiak** [comment]
haha, ok, something up with the repo then, i'll look at it tomorrow, way too tired to get deep into it right now :D

**Comment by fastgar** [comment]
okay wish you good look to solving the repo issue.

thx for help, issue is now closed.
