### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by night0wolfs** [EVE-KILL/zKillboard#331]
![e9a2c-clip-51kb](https://cloud.githubusercontent.com/assets/16705436/12328297/0105a85e-bb05-11e5-812c-1690418d865f.png)
Tell me, what mistake I put all the instructions:
Installation is handled via command line. Other methods are currently not supported.

```
cd to a dir where you want zKillboard to reside.
Do git clone git@github.com:EVE-KILL/zKillboard.git.
cd into zKillboard dir.
Get composer. curl -s https://getcomposer.org/installer | php
Install vendor files with composer. php composer.phar install
cd into install dir.
Execute the installation script. php5 install.php
Follow the instructions and fill in the prompts
Setup stomp (Follow guide further down)
Setup the CLI system.
Setup cronjobs
```

All the recommended settings are made

**Comment by kukonja6** [comment]
hello o7

when faced with the same problem on ubuntu 14.04, i fixed it by installing mariadb 10.1 - [link](https://downloads.mariadb.org/mariadb/repositories/#mirror=hs-esslingen)

**Comment by alucard0134** [comment]
Yes MySQL is not compatible with zkillboard and WILL run into issues with importing the db. Just migrate to MariaDB

**Comment by luminarium** [comment]
I have mariadb, still the same error 

Adding table ccp_zwormhole_info ... Error! Removing configuration file.
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect D' at row 1' in

**Comment by jsmb768ypl** [comment]
I don't plan to migrate to mariadb so I shouldn't expect to be able to install zkillboard?

**Comment by karbowiak** [comment]
@alucard0134 @luminarium @jsmb768ypl 

If you manually adapt every sql file before import (or manually create every table) it's doable, there is nothing in zKB that inherently requires it to be MariaDB - it's just the sql dumps that was made with MariaDB - and thus would prefer it was MariaDB.

I don't have a regular MySQL (or Percona) installation on hand right now, otherwise i'd be ok with making you guys some dumps :)

**Comment by jsmb768ypl** [comment]
@karbowiak thank you for that, I have no idea how to change sql dumps to be used with MySQL so I will look for a different kill board thanks!

**Comment by karbowiak** [comment]
kk, gl @jsmb768ypl :)

**Comment by luminarium** [comment]
mariadb ftw. grow up :)
