### ISSUE TITLE
Slim Application Error / GUI stuck

### ISSUE THREAD

**Issue by Wandie2000** [EVE-KILL/zKillboard#334]
Hi,

Got suddenly this message in GUI (was editing a node): Slim Application Error
Eve version: 5.0.1-19-Community

Type: ErrorException
Code: 8
Message: Undefined offset: 1
File: /opt/unetlab/html/includes/api_topology.php
Line: 108

ErrorException: Undefined offset: 1 in /opt/unetlab/html/includes/api_topology.php:108
Stack trace:
#0 /opt/unetlab/html/includes/api_topology.php(108): Slim\Slim::handleErrors()
#1 /opt/unetlab/html/api.php(624): apiGetLabTopology()
#2 [internal function]: {closure}()
#3 /opt/unetlab/html/includes/Slim/Route.php(468): call_user_func_array()
#4 /opt/unetlab/html/includes/Slim/Slim.php(1357): Slim\Route->dispatch()
#5 /opt/unetlab/html/includes/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /opt/unetlab/html/includes/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /opt/unetlab/html/includes/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 /opt/unetlab/html/includes/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#9 /opt/unetlab/html/api.php(1347): Slim\Slim->run()
#10 {main}
)

As a result, it is impossible to open the lab. As soon as I click, the error message appears and disappears immediately, and the lab does not open.

Need help please

Thanks

**Comment by karbowiak** [comment]
@Wandie2000 this doesn't seem like an issue related to zKillboard, which also hasn't seen any development in years.

zKillboard is a killboard for EVE-Online, what you're accessing seems to be some kind of Lab thing (hence LabTopology)
Sorry, i don't think i can help you

**Comment by karbowiak** [comment]
No problem @Wandie2000 - good luck! :)
